import type { Metadata } from 'next';
import '@/css/globals.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className="[--h-screen:100vh] supports-[height:1dvh]:[--h-screen:100dvh] supports-[height:1svh]:[--h-screen:100svh]"
    >
      <body className="antialiased min-h-(--h-screen) flex flex-col">
        <div className="flex flex-col flex-1 size-full">{children}</div>
      </body>
    </html>
  );
}
