import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { cx } from "@/css/cva";
import "@/css/globals.css";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className="[--h-screen:100vh] supports-[height:1dh]:[--h-screen:100dvh] supports-[height:1svh]:[--h-screen:100svh]"
    >
      <body className={cx(inter.variable, "antialiased min-h-(--h-screen) flex flex-col")}>
        <main className="flex flex-col">{children}</main>
      </body>
    </html>
  );
}
